### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by onmax**
- Update to the documentation
- New package for static policy

### CODE REVIEW

**Review by Albermonte — CHANGES_REQUESTED** [review]
When running in local I get this error:
```

 ERROR  [worker reload] [worker init] Unexpected number                                                                                                                                                                  2:33:45 PM

  at compileSourceTextModule (node:internal/modules/esm/utils:340:16)
  at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:102:18)
  at #translate (node:internal/modules/esm/loader:433:12)
  at ModuleLoader.loadAndTranslate (node:internal/modules/esm/loader:480:27)
 ```

**Comment by onmax** [comment]
Skill issues

**Comment by onmax** [comment]
There was an issue with the following statement:

```ts
export const PROOF_OF_WORK_EMISSION_SPEED = powi(2, 22)
```

Somehow, the bundler decided to convert `22` to a constant with the same name...

Since it is a constant, it didn't make sense to have a function call everytime so I have replace it with:

```ts
export const PROOF_OF_WORK_EMISSION_SPEED = 4_194_304 // same as powi(2, 22)
```


With that, `nuxi build` works again. 

The problem now is `nuxi dev`. Which keeps showing the same error...

I will keep checking

**Comment by onmax** [comment]
ok found it:

[`f996d6b` (#80)](https://github.com/nimiq/validators-api/pull/80/commits/f996d6b82dbc874a420a5f35643cbf3112b43ce4)

**Review by Albermonte — APPROVED** [review]
LGTM

**Pull request merged**
