### PR TITLE
add icon info for validator

### PR DESCRIPTION
**Pull request by gallareton**

### CODE REVIEW

**Comment by onmax** [comment]
Hey, thanks for your PR

You need to prepend `data:image/svg+xml;base64` in the icon:

```
data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OTkiIGhlaWdodD0iNDQwIj48cGF0aCBmaWxsPSIjRkZDMTA3IiBmaWxsLXJ1bGU9ImV2ZW5vZGQiIGQ9Ik0zODkgMjFjLTYtMTItMjMtMjEtMzYtMjFIMTQ1Yy0xMyAwLTI5IDktMzYgMjFMNSAxOTljLTYgMTEtNiAzMCAwIDQxbDEwNCAxNzhjNyAxMiAyMyAyMSAzNiAyMWgyMDhjMTQgMCAzMC05IDM2LTIxbDEwNC0xNzhjNy0xMSA3LTMwIDAtNDFMMzg5IDIxek0yNzMgMzQ3djQyaC0zOXYtNDBjLTI0LTMtNTItMTMtNzAtMzBsMjUtMzljMjEgMTUgMzggMjMgNTcgMjMgMjMgMCAzMy05IDMzLTI4IDAtNDAtMTA2LTM5LTEwNi0xMTEgMC0zOCAyMy02NSA2MS03M1Y1MWgzOXY0MGMyNSAzIDQ0IDE2IDU5IDMybC0yOSAzM2MtMTUtMTMtMjctMjAtNDQtMjAtMTkgMC0yOSA4LTI5IDI2IDAgMzcgMTA1IDM0IDEwNSAxMTAgMCAzNy0yMSA2Ny02MiA3NXoiLz48L3N2Zz4=
```

I recommend using `#FFC107` as the `accentColor`. `#ffffff` might blend in too much and could be less effective in most designs.

Let me know what you think! :)

**Comment by gallareton** [comment]
> Hey, thanks for your PR
> 
> You need to prepend `data:image/svg+xml;base64` in the icon:

Sure, will do, thank you for correction :)


> I recommend using `#FFC107` as the `accentColor`. `#ffffff` might blend in too much and could be less effective in most designs.
> 
> Let me know what you think! :)

What's the purpose of the accentColor? It's documented as "required when icon is set" but it's function isn't described

**Comment by onmax** [comment]
We don't use it much at the moment, but where we do use it is in a graphic I'm working on.

image

In the future, this `accentColor` might be used in other designs from us, but also from the community who want to build something cool :)

**Comment by onmax** [comment]
Thanks!

**Pull request merged**
