### PR TITLE
chore(garudapool): update pool details json

### PR DESCRIPTION
**Pull request by MelvishNiz**
My pool allows users to choose between **restake** or **direct** payouts. What should I set as the value for `payoutType`: **restake** or **direct**?

### CODE REVIEW

**Comment by onmax** [comment]
> My pool allows users to choose between restake or direct payouts. What should I set as the value for payoutType: restake or direct?

Hello. We may introduce a new value for `payoutType` for cases like this, but for now I would recommend using the default value that you have for `payoutType` and updating the description to let users know now that your pool is flexible.

I know this is not the best, but we are working on it...

**Comment by MelvishNiz** [comment]
okay then i updated my description. thanks

**Review by Albermonte — APPROVED** [review]

**Comment by MelvishNiz** [comment]
can we merge to `main` ?

**Comment by onmax** [comment]
Hey hello.

Sorry, the current process of verifying and validating the information you submit is quite slow and not very transparent.

If anything is off I will let you know in the PR.

Sorry about the inconvenience but we are working in a better approach.

Thanks for your patience

**Comment by MelvishNiz** [comment]
In my commit, I only updated my pool details. Could you please let me know what process is currently underway?

> Hey hello.
> 
> Sorry, the current process of verifying and validating the information you submit is quite slow and not very transparent.
> 
> If anything is off I will let you know in the PR.
> 
> Sorry about the inconvenience but we are working in a better approach.
> 
> Thanks for your patience

**Comment by onmax** [comment]
We need to verify that website is not malicious and the process can take a day or two.

**Pull request merged**
