### PR TITLE
Ritvars Staking website data has been updated

### PR DESCRIPTION
**Pull request by ritvarsbiksis**

### CODE REVIEW

**Comment by Albermonte** [comment]
Please, check linting

**Comment by ritvarsbiksis** [comment]
It wasn't in my file.
May I change other JSON files?

**Comment by ritvarsbiksis** [comment]
OK, No problem.

**Comment by Albermonte** [comment]
> It wasn't in my file. May I change other JSON files?

My bad, sorry. 
Thanks.

**Review by Albermonte — APPROVED** [review]

**Pull request merged**
