### PR TITLE
Update NQ98 D3KE 8EQ8 Y7DK G1MT 3P5T 2PHX 18V5 UEC1.json

### PR DESCRIPTION
**Pull request by hash0xf**
Add description, fee and payoutSchedule

### CODE REVIEW

**Comment by onmax** [comment]
Thank you! By any chance do you have SVG instead of png? Thanks

**Comment by hash0xf** [comment]
> Thank you! By any chance do you have SVG instead of png? Thanks

The original SVG file was much larger, I have already converted it to PNG, which reduced the size by 78%.

**Comment by onmax** [comment]
Ok, the issue is that it has a background. If you send me the svg, I can remove the background and convert it to png 🙂

**Comment by hash0xf** [comment]
> Ok, the issue is that it has a background. If you send me the svg, I can remove the background and convert it to png 🙂

moonpool_optimized

**Comment by onmax** [comment]
Thank you!

Just before we merge, a quick note

We have just added a [recommendations section](https://github.com/nimiq/validators-api#description) for validator descriptions to keep them clear and professional. Phrases like "to the Moooon and out of the Universe!" might not fully align with these.


Your description is your responsibility. We're not liable for any content you submit.
Keep in mind that descriptions implying financial outcomes could have legal consequences depending on the jurisdiction.


Feel free to tweak your description if needed, but it's your call. Let us know if you have any questions!


**We are not forcing you to change it but just letting you know**

**Comment by hash0xf** [comment]
> Thank you!
> 
> Just before we merge, a quick note
> 
> We have just added a [recommendations section](https://github.com/nimiq/validators-api#description) for validator descriptions to keep them clear and professional. Phrases like "to the Moooon and out of the Universe!" might not fully align with these.
> 
> Your description is your responsibility. We're not liable for any content you submit. Keep in mind that descriptions implying financial outcomes could have legal consequences depending on the jurisdiction.
> 
> Feel free to tweak your description if needed, but it's your call. Let us know if you have any questions!
> 
> **We are not forcing you to change it but just letting you know**

Let me fix it. Thanks.

**Review by onmax — APPROVED** [review]
Thanks!

**Pull request merged**
